services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: teste_conveste
    image: teste-conveste:1.0
    depends_on:
      - db
    env_file:
      - .env
    working_dir: /app
    command: python app.py
    volumes:
      - ./src:/app

volumes:
  postgres_data: